default: &default
  adapter: postgresql
  encoding: unicode
  database: task_manager_core
  pool: 5
  username: postgres
  password: postgres
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: db/task_manager_core/development

test:
  <<: *default
  database: db/task_manager_core/test

production:
  <<: *default
  database: db/task_manager_core/production
