image: docker:latest

stages:
  - test

variables:
  # use the overlay storage driver
  # https://docs.gitlab.com/ce/ci/docker/using_docker_build.html#using-the-overlayfs-driver
  DOCKER_DRIVER: overlay2
#
test:
  stage: test
  only:
    - master
    - merge_requests
  services:
    - docker:dind
  before_script:
    - apk add --no-cache docker-compose
    - docker-compose build
    - docker-compose up -d
    - docker-compose exec -T rails rake db:create
    - docker-compose exec -T rails rake db:migrate
  script:
    - docker-compose exec -T rails rspec
