image: docker:latest

stages:
  - test

test:
  stage: test
  services:
    - docker:dind
  before_script:
    - apk add --no-cache docker-compose
    - docker-compose build
    - docker-compose run rails rake db:create
    - docker-compose exec rails rake db:migrate
    - docker-compose exec rails rake db:seed
  script:
    - docker-compose exec rails rspec
