image: docker:latest

stages:
  - test
  - deploy heroku
  - deploy coverage
variables:
  # use the overlay storage driver
  # https://docs.gitlab.com/ce/ci/docker/using_docker_build.html#using-the-overlayfs-driver
  DOCKER_DRIVER: overlay2
#
test:
  stage: test
  coverage: '/LOC\s\(\d+\.\d+%\)\scovered/'
  only:
    - master
    - merge_requests
    - external_pull_requests
  services:
    - docker:dind
  before_script:
    - apk add --no-cache docker-compose
    - docker-compose build
    - docker-compose up -d
    - docker-compose exec -T rails rake db:create
    - docker-compose exec -T rails rake db:migrate
  script:
    - docker-compose exec -T rails rspec
  artifacts:
    paths:
      - "volume/tasks-manager/coverage/"
    name: "Pipeline $CI_PIPELINE_ID Coverage Report"

deploy:
  stage: deploy heroku
  before_script: -  apk add curl nodejs bash
    -  curl https://cli-assets.heroku.com/install.sh | sh
  script:
    -  heroku container:login
    - heroku container:push web --app =$HEROKU_APP_STAGING
    - heroku container:release web

  # script:
  #   - docker build -f Dockerfile --iidfile imageid.txt -t registry.heroku.com/edimossilva-task-manager/my-app .
  #   - docker login -u _ -p $HEROKU_API_KEY registry.heroku.com
  #   - docker push registry.heroku.com/edimossilva-task-manager/my-app
  #   - apk add --no-cache curl
  #   - echo "Docker Image ID is $(cat imageid.txt)"
  #   - |-
  #     curl -X PATCH https://api.heroku.com/apps/edimossilva-task-manager/formation --header "Content-Type: application/json" --header "Accept: application/vnd.heroku+json; version=3.docker-releases" --header "Authorization: Bearer ${HEROKU_API_KEY}" --data '{ "updates": [ { "type": "web", "docker_image": "'$(cat imageid.txt)'" } ] }'

pages:
  stage: deploy coverage
  only:
    - master
    - merge_requests
    - external_pull_requests
  dependencies:
    - test
  script:
    - mv volume/tasks-manager/coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
