image: docker

stages:
  - test

test:
  stage: test
  services:
    - docker:dind
  before_script:
    - apk add --no-cache python py2-pip git
    - pip install --no-cache-dir docker-compose
    - docker-compose build
    - docker-compose run rails rake db:create
    - docker-compose exec rails rake db:migrate
    - docker-compose exec rails rake db:seed
  script:
    - docker-compose exec rails rspec
