image: docker:latest

stages:
  - test
  - deploy
  - test deploy
variables:
  # use the overlay storage driver
  # https://docs.gitlab.com/ce/ci/docker/using_docker_build.html#using-the-overlayfs-driver
  DOCKER_DRIVER: overlay2
#
test tasks_manager_core:
  stage: test
  coverage: '/LOC\s\(\d+\.\d+%\)\scovered/'
  only:
    - master
    - merge_requests
    - external_pull_requests
  services:
    - docker:dind
  before_script:
    - apk add --no-cache docker-compose
    - docker-compose build tasks_manager_core
    - docker-compose up -d tasks_manager_core
    - docker-compose exec -T tasks_manager_core rake db:create db:migrate
  script:
    - docker-compose exec -T tasks_manager_core rspec
  after_script:
    - mv volume/tasks-manager-core/coverage/index.html volume/tasks-manager-core/coverage/tasks_manager_core_coverage.html
  artifacts:
    paths:
      - "volume/tasks-manager-core/coverage/"
    name: "Pipeline $CI_PIPELINE_ID Coverage Report"

test auth_provider:
  stage: test
  coverage: '/LOC\s\(\d+\.\d+%\)\scovered/'
  only:
    - master
    - merge_requests
    - external_pull_requests
  services:
    - docker:dind
  before_script:
    - apk add --no-cache docker-compose
    - docker-compose build auth_provider
    - docker-compose up -d auth_provider
    - docker-compose exec -T auth_provider rake db:create db:migrate
  script:
    - docker-compose exec -T auth_provider rspec
  after_script:
    - cp volume/auth-provider/coverage/index.html volume/auth-provider/coverage/auth_provider_coverage.html

  artifacts:
    paths:
      - "volume/auth-provider/coverage/"
    name: "Pipeline $CI_PIPELINE_ID Coverage Report"

test auth_provider:
  stage: test
  coverage: '/LOC\s\(\d+\.\d+%\)\scovered/'
  only:
    - master
    - merge_requests
    - external_pull_requests
  services:
    - docker:dind
  before_script:
    - apk add --no-cache docker-compose
    - docker-compose build auth_provider
    - docker-compose up -d auth_provider
    - docker-compose exec -T auth_provider rake db:create db:migrate
  script:
    - docker-compose exec -T auth_provider rspec
  after_script:
    - cp volume/auth-provider/coverage/index.html volume/auth-provider/coverage/auth_provider_coverage.html

  artifacts:
    paths:
      - "volume/auth-provider/coverage/"
    name: "Pipeline $CI_PIPELINE_ID Coverage Report"

deploy heroku:
  stage: deploy
  only:
    - master
    - merge_requests
    - external_pull_requests
  services:
    - docker:dind
  before_script:
    - apk add curl nodejs bash git
    -  curl https://cli-assets.heroku.com/install.sh | sh
    - docker build .
  script:
    - docker build -f Dockerfile -t registry.heroku.com/edimossilva-task-manager/tasks-manager-core .
    - docker login -u _ -p $HEROKU_API_KEY registry.heroku.com
    - docker push registry.heroku.com/edimossilva-task-manager/tasks-manager-core
    -  heroku container:login
    - heroku run rails db:migrate db:seed --app=$HEROKU_APP_STAGING


test deploy heroku:
  image: curlimages/curl
  only:
    - master
    - merge_requests
    - external_pull_requests
  stage: test deploy
  script:
    - curl -s "https://edimossilva-task-manager.herokuapp.com/apipie" | grep -q "half minute and a half"

pages:
  stage: deploy
  only:
    - master
    - merge_requests
    - external_pull_requests
  dependencies:
    - test tasks_manager_core
    - test auth_provider
  script:
    - mv volume/tasks-manager-core/coverage/* public
    - mv volume/auth-provider/coverage/auth_provider_coverage.html public
    - cp pages/index.html public/index.html
  artifacts:
    paths:
      - public
    expire_in: 100 days
