image: docker

stages:
  - test

test:
  stage: test
  services:
    - docker:dind
  before_script:
    - sudo curl -L "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    - sudo chmod +x /usr/local/bin/docker-compose
    - sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
    - docker-compose build
    - docker-compose run rails rake db:create
    - docker-compose exec rails rake db:migrate
    - docker-compose exec rails rake db:seed
  script:
    - docker-compose exec rails rspec
