image: docker:latest

stages:
  - test
  - deploy
  - test deploy
variables:
  # use the overlay storage driver
  # https://docs.gitlab.com/ce/ci/docker/using_docker_build.html#using-the-overlayfs-driver
  DOCKER_DRIVER: overlay2
#
test:
  stage: test
  coverage: '/LOC\s\(\d+\.\d+%\)\scovered/'
  only:
    - master
    - merge_requests
    - external_pull_requests
  services:
    - docker:dind
  before_script:
    - apk add --no-cache docker-compose
    - docker-compose build
    - docker-compose up -d
    - docker-compose exec -T rails rake db:create
    - docker-compose exec -T rails rake db:migrate
  script:
    - docker-compose exec -T rails rspec
  artifacts:
    paths:
      - "volume/tasks-manager/coverage/"
    name: "Pipeline $CI_PIPELINE_ID Coverage Report"

deploy heroku:
  stage: deploy
  only:
    - master
    - merge_requests
    - external_pull_requests
  services:
    - docker:dind
  before_script:
    - apk add curl nodejs bash git
    -  curl https://cli-assets.heroku.com/install.sh | sh
    - docker build .
  script:
    -  heroku container:login
    - heroku git:remote -a $HEROKU_APP_STAGING
    - echo $HEROKU_APP_STAGING
    - heroku container:push web
    - heroku container:release web
    - heroku run rails db:migrate
    - heroku run rails db:seed

test deploy heroku:
  image: curlimages/curl
  only:
    - master
    - merge_requests
    - external_pull_requests
  stage: test deploy
  script:
    - curl -s "https://edimossilva-task-manager.herokuapp.com/apipie" | grep -q "half minute and a half"

pages:
  stage: deploy
  only:
    - master
    - merge_requests
    - external_pull_requests
  dependencies:
    - test
  script:
    - mv volume/tasks-manager/coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
