version: "3"
services:
  db:
    image: postgres
    container_name: db
    volumes:
      - ./config/postgres-data:/var/lib/postgresql/data

    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "5432:5432"

  # message_broker:
  #   image: "rabbitmq:3.8-management-alpine"
  #   container_name: message_broker
  #   environment:
  #     RABBITMQ_DEFAULT_USER: "admin"
  #     RABBITMQ_DEFAULT_PASS: "admin"
  #   ports:
  #     - "15672:15672"
  #     - "5672:5672"

  rails:
    build:
      context: "."
      dockerfile: "Dockerfile"
    container_name: rails
    volumes:
      - ./volume/tasks-manager:/app
    depends_on:
      - db
      # - message_broker
    environment:
      RUBYOPT: "-W:no-deprecated -W:no-experimental"
      RAILS_MASTER_KEY: "a667717bf0a47475b0582547379c816d"
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"
      DATABASE_URL: "postgres://db"
    tty: true
    command: puma
    ports:
      - "3000:3000"
# docker-compose build
# docker-compose up -d
# docker-compose exec rails rake db:create
# docker-compose exec rails rake db:migrate
# docker-compose exec rails rake db:seed
# docker-compose exec rails rspec
# localhost:3000
