default: &default
  adapter: postgresql
  encoding: unicode
  database: auth_provider_database
  pool: 5
  username: postgres
  password: postgres
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: db/auth_provider_database/development

test:
  <<: *default
  database: db/auth_provider_database/test

production:
  <<: *default
  database: db/auth_provider_database/production
